server:
  port: 8090
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: reservations-service
  lifecycle:
    timeout-per-shutdown-phase: 15s

  r2dbc:
    username: root
    password: 1234
    url: r2dbc:mysql://localhost:3306/petclinic_reservations
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10

petclinic:
  vet-service-uri: "http://localhost:8080"
