server:
  port: 8080

spring:
  active:
    on-profile: default
    
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic_vetman
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  show-sql: true
  format-sql: true
